{
 "title": "SR Linux Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   {
    "name": "Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "DC fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:IN"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Link Bandwidth",
   "type": "canvas",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    {
     "expr": "gnmic_srl_if_oper_state_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    }
   ]
  },
  {
   "title": "Front panel view",
   "type": "canvas",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "(gnmic_srl_if_traffic_rate_in_bps + gnmic_srl_if_traffic_rate_out_bps)",
     "legendFormat": "{{source}}:{{interface_name}} "
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_disabled_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_total_received_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_srl_cpu_instant{source=\"$NE\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "gnmic_srl_mem_free{source=\"$NE\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "gnmic_srl_mem_utilization{source=\"$NE\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "gnmic_srl_mem_reserved{source=\"$NE\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "gnmic_srl_mem_physical{source=\"$NE\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Service: $Services",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "gnmic_srl_net_instance_oper_state{network_instance_name='$Services'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "gnmic_srl_apps_pid{source='$NE'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  { "title": "Logging $NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Log: $Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{application=\"$Logs\", source=\"$NE\"}"
    }
   ]
  },
  {
   "title": "Total logs $NE",
   "type": "piechart",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=\"$NE\"}[$__range]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Log volume: $Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({application=\"$Logs\",source=\"$NE\"} | logfmt [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}